sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jfbill/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true jfbill/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-759940727831"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"    
    